/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SitePollutionTestingRouteImport } from './routes/_site.pollution-testing'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteBlogRouteImport } from './routes/_site.blog'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppPortalIndexRouteImport } from './routes/_app.portal.index'
import { Route as AppPortalRequestsRouteImport } from './routes/_app.portal.requests'
import { Route as AppPortalQuoteRouteImport } from './routes/_app.portal.quote'
import { Route as AppPortalProfileRouteImport } from './routes/_app.portal.profile'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SitePollutionTestingRoute = SitePollutionTestingRouteImport.update({
  id: '/pollution-testing',
  path: '/pollution-testing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalIndexRoute = AppPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRequestsRoute = AppPortalRequestsRouteImport.update({
  id: '/portal/requests',
  path: '/portal/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalQuoteRoute = AppPortalQuoteRouteImport.update({
  id: '/portal/quote',
  path: '/portal/quote',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalProfileRoute = AppPortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/pollution-testing': typeof SitePollutionTestingRoute
  '/services': typeof SiteServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/portal/profile': typeof AppPortalProfileRoute
  '/portal/quote': typeof AppPortalQuoteRoute
  '/portal/requests': typeof AppPortalRequestsRoute
  '/portal/': typeof AppPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/pollution-testing': typeof SitePollutionTestingRoute
  '/services': typeof SiteServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/portal/profile': typeof AppPortalProfileRoute
  '/portal/quote': typeof AppPortalQuoteRoute
  '/portal/requests': typeof AppPortalRequestsRoute
  '/portal': typeof AppPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/blog': typeof SiteBlogRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/pollution-testing': typeof SitePollutionTestingRoute
  '/_site/services': typeof SiteServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/_app/portal/profile': typeof AppPortalProfileRoute
  '/_app/portal/quote': typeof AppPortalQuoteRoute
  '/_app/portal/requests': typeof AppPortalRequestsRoute
  '/_app/portal/': typeof AppPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/pollution-testing'
    | '/services'
    | '/admin/login'
    | '/portal/profile'
    | '/portal/quote'
    | '/portal/requests'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/pollution-testing'
    | '/services'
    | '/admin/login'
    | '/portal/profile'
    | '/portal/quote'
    | '/portal/requests'
    | '/portal'
  id:
    | '__root__'
    | '/_app'
    | '/_site'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_site/about'
    | '/_site/blog'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/pollution-testing'
    | '/_site/services'
    | '/admin/login'
    | '/_site/'
    | '/_app/portal/profile'
    | '/_app/portal/quote'
    | '/_app/portal/requests'
    | '/_app/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pollution-testing': {
      id: '/_site/pollution-testing'
      path: '/pollution-testing'
      fullPath: '/pollution-testing'
      preLoaderRoute: typeof SitePollutionTestingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/': {
      id: '/_app/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AppPortalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/requests': {
      id: '/_app/portal/requests'
      path: '/portal/requests'
      fullPath: '/portal/requests'
      preLoaderRoute: typeof AppPortalRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/quote': {
      id: '/_app/portal/quote'
      path: '/portal/quote'
      fullPath: '/portal/quote'
      preLoaderRoute: typeof AppPortalQuoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/profile': {
      id: '/_app/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AppPortalProfileRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppPortalProfileRoute: typeof AppPortalProfileRoute
  AppPortalQuoteRoute: typeof AppPortalQuoteRoute
  AppPortalRequestsRoute: typeof AppPortalRequestsRoute
  AppPortalIndexRoute: typeof AppPortalIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppPortalProfileRoute: AppPortalProfileRoute,
  AppPortalQuoteRoute: AppPortalQuoteRoute,
  AppPortalRequestsRoute: AppPortalRequestsRoute,
  AppPortalIndexRoute: AppPortalIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBlogRoute: typeof SiteBlogRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SitePollutionTestingRoute: typeof SitePollutionTestingRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBlogRoute: SiteBlogRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SitePollutionTestingRoute: SitePollutionTestingRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
